source 'https://rubygems.org'

ruby '3.2.0'

# Web Framework
gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'
gem 'rack', '~> 3.0'

# Database
gem 'sqlite3', '~> 1.6'
gem 'activerecord', '~> 7.0'
gem 'sinatra-activerecord', '~> 2.0'

# Authentication & Security
gem 'bcrypt', '~> 3.1'
gem 'jwt', '~> 2.7'
gem 'rack-protection', '~> 3.0'

# API & HTTP
gem 'httparty', '~> 0.21'
gem 'json', '~> 2.6'
gem 'net-http-persistent', '~> 4.0'

# Background Jobs
gem 'sidekiq', '~> 7.0'
gem 'redis', '~> 5.0'

# Utilities
gem 'dotenv', '~> 0.3'
gem 'logger', '~> 1.5'
gem 'time', '~> 0.2'
gem 'digest', '~> 3.1'
gem 'erb', '~> 4.0'
gem 'uri', '~> 0.12'
gem 'open3', '~> 0.1'
gem 'date', '~> 3.2'

# Development
gem 'puma', '~> 6.0'
gem 'thin', '~> 1.8'

group :development do
  gem 'rerun', '~> 0.14'
  gem 'rack-livereload', '~> 0.3'
end

group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.0'
end 