# Ultimate Anti-Detection Configuration
# This file contains all settings for the anti-detection system

# Safety Levels
safety_levels:
  conservative:
    daily_limit: 20
    hourly_limit: 3
    base_delay: 300  # 5 minutes
    risk_multiplier: 2.0
    break_frequency: 0.3  # 30% chance of break
    session_duration: 30.minutes
    max_consecutive_actions: 5
    
  balanced:
    daily_limit: 50
    hourly_limit: 8
    base_delay: 180  # 3 minutes
    risk_multiplier: 1.5
    break_frequency: 0.15  # 15% chance of break
    session_duration: 60.minutes
    max_consecutive_actions: 10
    
  aggressive:
    daily_limit: 80
    hourly_limit: 15
    base_delay: 120  # 2 minutes
    risk_multiplier: 1.2
    break_frequency: 0.05  # 5% chance of break
    session_duration: 120.minutes
    max_consecutive_actions: 20

# Time-based Factors
time_factors:
  peak_hours:
    - 9..11   # Morning peak
    - 19..22  # Evening peak
    multiplier: 1.5
    
  off_peak_hours:
    - 2..6    # Late night
    multiplier: 0.7
    
  normal_hours:
    multiplier: 1.0

# Account Age Factors
account_age_factors:
  new_accounts:
    max_days: 30
    multiplier: 2.0
    daily_limit_reduction: 0.5
    
  young_accounts:
    max_days: 90
    multiplier: 1.5
    daily_limit_reduction: 0.7
    
  mature_accounts:
    max_days: 365
    multiplier: 1.2
    daily_limit_reduction: 0.9
    
  old_accounts:
    multiplier: 1.0
    daily_limit_reduction: 1.0

# Follower Count Factors
follower_factors:
  low_followers:
    max_count: 100
    multiplier: 1.8
    daily_limit_reduction: 0.6
    
  medium_followers:
    max_count: 500
    multiplier: 1.3
    daily_limit_reduction: 0.8
    
  high_followers:
    max_count: 1000
    multiplier: 1.0
    daily_limit_reduction: 1.0
    
  very_high_followers:
    multiplier: 0.8
    daily_limit_reduction: 1.2

# Action Delays (in seconds)
action_delays:
  follow:
    min: 120
    max: 300
    base: 180
    
  unfollow:
    min: 180
    max: 420
    base: 300
    
  like:
    min: 60
    max: 180
    base: 120
    
  comment:
    min: 300
    max: 600
    base: 450
    
  share:
    min: 600
    max: 1200
    base: 900

# Break Durations (in seconds)
break_durations:
  short_break:
    min: 300   # 5 minutes
    max: 900   # 15 minutes
    
  medium_break:
    min: 900   # 15 minutes
    max: 3600  # 1 hour
    
  long_break:
    min: 3600  # 1 hour
    max: 7200  # 2 hours
    
  extended_break:
    min: 7200  # 2 hours
    max: 21600 # 6 hours

# Session Management
session_management:
  max_session_duration: 7200  # 2 hours
  min_session_duration: 1800  # 30 minutes
  session_break_probability: 0.15  # 15% chance to end session
  
# Human Behavior Simulation
human_behavior:
  thinking_time:
    min: 2
    max: 8
    
  typing_time:
    min: 1
    max: 5
    
  reading_time:
    min: 3
    max: 12
    
  mouse_movement_delay:
    min: 1
    max: 3
    
  scroll_delay:
    min: 2
    max: 5

# Pattern Randomization
pattern_randomization:
  action_sequence_variation: 0.3  # 30% variation in action order
  timing_pattern_variation: 0.2   # 20% variation in timing
  random_action_probability: 0.1  # 10% chance of random action
  
# Safety Thresholds
safety_thresholds:
  max_consecutive_failures: 3
  max_hourly_actions: 15
  max_daily_actions: 100
  min_safety_score: 30
  critical_safety_score: 50
  
# Warning Levels
warning_levels:
  low_risk:
    safety_score: 85..100
    action: "Continue with monitoring"
    
  medium_risk:
    safety_score: 60..84
    action: "Reduce activity, increase delays"
    
  high_risk:
    safety_score: 30..59
    action: "Pause account, take extended break"
    
  critical_risk:
    safety_score: 0..29
    action: "Immediate pause, 24-hour break"

# Account Rotation
account_rotation:
  rotation_interval: 14400  # 4 hours
  min_rotation_interval: 7200   # 2 hours
  max_rotation_interval: 21600  # 6 hours
  priority_score_weights:
    recent_usage: 0.3
    daily_usage: 0.3
    account_age: 0.2
    follower_count: 0.2

# Target Selection
target_selection:
  avoid_recent_targets: true
  recent_target_window: 86400  # 24 hours
  target_diversity_factor: 0.8
  max_targets_per_session: 50

# Monitoring and Alerts
monitoring:
  check_interval: 300  # 5 minutes
  alert_thresholds:
    safety_score_drop: 10
    consecutive_failures: 3
    hourly_action_spike: 20
    
# Recovery Strategies
recovery_strategies:
  after_failure:
    delay_multiplier: 2.0
    break_duration: 1800  # 30 minutes
    
  after_suspension:
    delay_multiplier: 3.0
    break_duration: 7200  # 2 hours
    
  after_warning:
    delay_multiplier: 1.5
    break_duration: 3600  # 1 hour 